### ISSUE TITLE
Read Each Point In Files Classificaiton

### ISSUE THREAD

**Issue by chrisstayte** [assismauro/csharpLiDAR#1]
I get an error when I try to print out each points classification

**Comment by assismauro** [comment]
Chris,

Sorry, I didn´t see your comment. Could you please tell me more about this error, maybe send to me a piece of code?

Tks,

Mauro

**Comment by chrisstayte** [comment]
No worries! I was using an older version of las and it didn't have the data I was looking for! Just a data error! The class worked great! :)

Sent from my iPhone

On Feb 28, 2017, at 1:00 PM, Mauro Assis <notifications@github.com> wrote:

Reopened #1.

**Comment by assismauro** [comment]
Nice! If you have some other question, feel free to contact me.

I´ve something written in Python about LiDAR as well: https://github.com/assismauro/pyLiDARForest.

**Comment by chrisstayte** [comment]
Thanks! This is awesome! Keep up the awesome work 

Sent from my iPhone

On Feb 28, 2017, at 1:50 PM, Mauro Assis <notifications@github.com> wrote:

Nice! If you have some other question, feel free to contact me.

I´ve something written in Python about LiDAR as well: https://github.com/assismauro/pyLiDARForest.
